apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: hostpath-provisioner
  name: hostpath-provisioner
  namespace: kube-system
spec:
  template:
    metadata:
      name: hostpath-provisioner
      labels:
        app: hostpath-provisioner
    spec:
      nodeSelector:
        nailgun.name/hostpath: enabled
      # serviceAccount: hostpath-provisioner
      containers:
      - name: hostpath-provisioner
        image: hostpath-provisioner:latest
        args: ['-root', '/host']
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: hostRoot
          mountPath: /host
      volumes:
      - name: hostRoot
        hostPath:
          path: /
